name: Main build

on:
    pull_request:
        branches:
            - '**'
    push:
        branches:
            - develop
            - staging
            - master

jobs:
    test:
        if: github.ref_name == 'develop' || github.ref_name == 'staging' || github.ref_name == 'master'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.17.0
                  cache: 'yarn'

            # - name: Install Dependencies
            #   run: yarn install

            # - name: Run Tests
            #   run: yarn run test

    deploy:
        runs-on: ubuntu-latest
        needs: test
        # Dynamically set the environment based on the branch name
        environment: ${{
            github.ref_name == 'develop' && 'dev' ||
            github.ref_name == 'staging' && 'staging' ||
            github.ref_name == 'master' && 'prod' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.17.0
                  cache: 'yarn'

            - name: Install Serverless and Plugins
              run: |
                  yarn global add serverless@4.2.1
                  yarn add serverless-domain-manager@7.1.2

            - name: Set Environment Variables
              run: |
                  echo "STAGE=${{ github.ref_name == 'develop' && 'dev' || github.ref_name == 'staging' && 'staging' || github.ref_name == 'master' && 'prod' }}" >> $GITHUB_ENV
                  echo "REGION=${{ vars.AWS_REGION }}" >> $GITHUB_ENV

                  echo "CUSTOM_API_DOMAIN=${{ vars.CUSTOM_API_DOMAIN }}" >> $GITHUB_ENV

                  echo "VERSION_LAMBDA_FUNCTIONS=${{ vars.VERSION_LAMBDA_FUNCTIONS }}" >> $GITHUB_ENV

                  echo "TOKEN_REFRESH_RATE=${{ vars.TOKEN_REFRESH_RATE }}" >> $GITHUB_ENV

            - name: Set Environment Secrets
              run: |
                  echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> $GITHUB_ENV
                  echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> $GITHUB_ENV

                  echo "SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}" >> $GITHUB_ENV

                  echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
                  echo "AWS_LAMBDA_SECURITY_GROUP_ID=${{ secrets.AWS_LAMBDA_SECURITY_GROUP_ID }}" >> $GITHUB_ENV
                  echo "AWS_SUBNET_A=${{ secrets.AWS_SUBNET_A }}" >> $GITHUB_ENV
                  echo "AWS_SUBNET_B=${{ secrets.AWS_SUBNET_B }}" >> $GITHUB_ENV
                  echo "AWS_SUBNET_C=${{ secrets.AWS_SUBNET_C }}" >> $GITHUB_ENV
                  echo "API_ID=${{ secrets.AWS_API_ID }}" >> $GITHUB_ENV
                  echo "KMS_ENCRYPTION_KEY_ID=${{ secrets.KMS_ENCRYPTION_KEY_ID }}" >> $GITHUB_ENV

                  echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> $GITHUB_ENV
                  echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> $GITHUB_ENV

                  echo "JEST_API_KEY=${{ secrets.JEST_API_KEY }}" >> $GITHUB_ENV

            - name: Deploy
              run: |
                  serverless deploy --stage $STAGE --conceal --verbose
    release:
        if: github.ref_name == 'master'
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Release with Sentry
              run: |
                  yarn add @sentry/cli
                  sentry-cli releases finalize $(npm pkg get version | tr -d '"')
                  sentry-cli sourcemaps inject --org normal-finance --project api .webpack && sentry-cli sourcemaps upload --org normal-finance --project stellar-crank .webpack
